# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9deb8e1a0963456f446c61d51039ab028707ca5b14dd401086f64965d5c86b1b74af384006fcebd15e27ff2b6a7c70d629be991c9c9983f73ebf8d7cd003d42

test:
  secret_key_base: b381617522e4454d0c7e8dafa4cd886c156fca90ad2ea5b0dd61137602117fb0d8044b6af2f809752a2d74dd75011e37ff29bfeb0399d2976ae431cdf2b7eb51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
